---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.26.0
    hooks:
      - id: sqlfmt
        language_version: python3.13
        additional_dependencies: ['.[jinjafmt]']
        exclude: '^scripts/'
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        args: [-conf, .yamlfmt]
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.7
    hooks:
      - id: dbt-deps
      - id: dbt-parse
      - id: dbt-docs-generate
        args: ["--cmd-flags", "++no-compile"]
      - id: check-script-semicolon
        exclude: '(jobs|scripts)/.*'
      - id: check-script-has-no-table-name
        exclude: '(jobs|scripts)/.*'
      - id: check-model-has-all-columns
        name: Check columns - core
        files: ^models/core
      # - id: check-model-has-all-columns
      #   name: Check columns - mart
      #   files: ^models/mart
      - id: check-model-columns-have-desc
        files: ^models/mart
