---
name: 'snowflake_dbt_demo'
version: '0.1.0'
profile: 'snowflake_dbt_demo'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
flags:
  send_anonymous_usage_stats: False
  use_colors: True
data_tests:
  dbt_project_evaluator:
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"
seeds:
  snowflake_dbt_demo:
    +schema: seeds
snapshots:
  snowflake_dbt_demo:
    +schema: snapshots
models:
  dbt_project_evaluator:
    +schema: metadata
    +enabled: "{{ env_var('DBT_PROJECT_EVALUATOR_ENABLED', 'false') | lower == 'true' | as_bool }}"
  snowflake_dbt_demo:
    +persist_docs:
      relation: true
      columns: true
    intermediate:
      +schema: intermediate
      +access: protected
    staging:
      +schema: staging
      +access: protected
    marts:
      +database: |
        demo_{{ env_var('ENVIRONMENT', 'dev') }}_marts
      +access: public
      +materialized: view
      finance:
        +schema: finance
      marketing:
        +schema: marketing
      operations:
        +schema: operations
      public:
        +schema: public
      sales:
        +schema: sales
