---
name: 'snowflake_dbt_demo'
version: '1.0.0'
profile: 'snowflake_dbt_demo'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
flags:
  send_anonymous_usage_stats: False
  use_colors: True
snapshots:
  snowflake_dbt_demo:
    +schema: snapshot
models:
  dbt_project_evaluator:
    +schema: metadata
    +enabled: "{{ env_var('DBT_PROJECT_EVALUATOR_ENABLED', 'false') | lower == 'true' | as_bool }}"
  snowflake_dbt_demo:
    +persist_docs:
      relation: true
      columns: true
    intermediate:
      +schema: intermediate
      +access: protected
    staging:
      +schema: staging
      +access: protected
    mart:
      core:
        +access: public
        +schema: mart
        +materialized: table
