with
    web_page as (select * from {{ ref("stg_tpcds_web_page") }}),
    final as (
        select
            web_page_key,
            web_page_id,
            url,
            type,
            is_autogenerated = 'Y' as is_autogenerated,
            character_count,
            link_count,
            image_count,
            max_ad_count,
            customer_key,
            creation_date_key,
            access_date_key,
            record_start_date,
            record_end_date,
            record_end_date is null as is_current_record
        from web_page
    )
select *
from final
