use role demo_data_developer
;
CREATE OR REPLACE TASK DEMO_<% ctx.env.ENVIRONMENT %>_ANALYTICS.INTERNAL.DBT_BUILD_FULL_REFRESH
  WAREHOUSE = DEMO_TRANSFORM_XS
AS
  EXECUTE DBT PROJECT DEMO_<% ctx.env.ENVIRONMENT %>_ANALYTICS.INTERNAL.SNOWFLAKE_DBT_DEMO args='build --full-refresh';
