use role demo_data_developer
;
CREATE OR REPLACE TASK DEMO_<% ctx.env.ENVIRONMENT %>_ANALYTICS.INTERNAL.DBT_SCHEDULE_DAILY_BUILD
  WAREHOUSE = DEMO_TRANSFORM_XS
  SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
  EXECUTE DBT PROJECT DEMO_<% ctx.env.ENVIRONMENT %>_ANALYTICS.INTERNAL.SNOWFLAKE_DBT_DEMO args='build';

ALTER TASK DEMO_<% ctx.env.ENVIRONMENT %>_ANALYTICS.INTERNAL.DBT_SCHEDULE_DAILY_BUILD RESUME;
