USE SECONDARY ROLES ALL;

-- USERS
USE ROLE SECURITYADMIN;
CREATE OR REPLACE USER "GITHUB@DEMO.LOCAL"
    TYPE = SERVICE
    WORKLOAD_IDENTITY = (
        TYPE = OIDC ISSUER = 'https://token.actions.githubusercontent.com'
        SUBJECT = 'repo:memadore/snowflake-dbt-demo:ref:refs/heads/main'
);

-- RBAC
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE PLATFORM_ADMIN;
GRANT ROLE PLATFORM_ADMIN TO ROLE SYSADMIN;

CREATE OR REPLACE ROLE DEMO_ADMIN;
GRANT ROLE DEMO_ADMIN TO ROLE PLATFORM_ADMIN;

CREATE OR REPLACE ROLE DEMO_DATA_DEVELOPER;
GRANT ROLE DEMO_DATA_DEVELOPER TO USER "GITHUB@DEMO.LOCAL";
GRANT ROLE DEMO_DATA_DEVELOPER TO ROLE DEMO_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DEMO_DATA_DEVELOPER;

CREATE OR REPLACE ROLE DEMO_DATA_ANALYST;
GRANT ROLE DEMO_DATA_ANALYST TO ROLE DEMO_DATA_DEVELOPER;

CREATE OR REPLACE ROLE DEMO_DATA_VIEWER;
GRANT ROLE DEMO_DATA_VIEWER TO ROLE DEMO_DATA_ANALYST;

-- WAREHOUSES
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE PLATFORM_ADMIN_XS WITH
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE;
GRANT OWNERSHIP ON WAREHOUSE PLATFORM_ADMIN_XS TO ROLE PLATFORM_ADMIN;

CREATE OR REPLACE WAREHOUSE DEMO_TRANSFORM_XS WITH
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE;
GRANT OWNERSHIP ON WAREHOUSE DEMO_TRANSFORM_XS TO ROLE DEMO_ADMIN;

CREATE OR REPLACE WAREHOUSE DEMO_EXPLORATION_XS WITH
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE;
GRANT OWNERSHIP ON WAREHOUSE DEMO_EXPLORATION_XS TO ROLE DEMO_ADMIN;

CREATE OR REPLACE WAREHOUSE DEMO_REPORTING_XS WITH
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE;
GRANT OWNERSHIP ON WAREHOUSE DEMO_REPORTING_XS TO ROLE DEMO_ADMIN;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE PLATFORM_ADMIN_XS TO USER "GITHUB@DEMO.LOCAL";
GRANT USAGE ON WAREHOUSE DEMO_TRANSFORM_XS TO ROLE DEMO_DATA_DEVELOPER;
GRANT USAGE ON WAREHOUSE DEMO_EXPLORATION_XS TO ROLE DEMO_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE DEMO_REPORTING_XS TO ROLE DEMO_DATA_VIEWER;

-- DATABASE
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE DEMO_DEV_ANALYTICS;
GRANT OWNERSHIP ON DATABASE DEMO_DEV_ANALYTICS TO ROLE PLATFORM_ADMIN;
DROP SCHEMA DEMO_DEV_ANALYTICS.PUBLIC;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.STAGING;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.STAGING TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.MART;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.MART TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.REPORTS;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.REPORTS TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.SEEDS;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.SEEDS TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.SNAPSHOTS;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.SNAPSHOTS TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.INTERNAL;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.INTERNAL TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.METADATA;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.METADATA TO ROLE DEMO_ADMIN;
CREATE OR REPLACE SCHEMA DEMO_DEV_ANALYTICS.WORKSPACE;
GRANT OWNERSHIP ON SCHEMA DEMO_DEV_ANALYTICS.WORKSPACE TO ROLE DEMO_ADMIN;

CREATE OR REPLACE DATABASE ROLE DEMO_DEV_ANALYTICS.ADMIN;
GRANT ALL PRIVILEGES ON DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.ADMIN;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.ADMIN;

CREATE OR REPLACE DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER;
GRANT DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER TO DATABASE ROLE DEMO_DEV_ANALYTICS.ADMIN;
GRANT USAGE, CREATE SCHEMA, MONITOR ON DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER;
GRANT USAGE, MONITOR, CREATE TEMPORARY TABLE, CREATE TAG, CREATE PIPE, CREATE PROCEDURE, CREATE MATERIALIZED VIEW, CREATE TABLE, CREATE FILE FORMAT, CREATE STAGE, CREATE TASK, CREATE FUNCTION, CREATE EXTERNAL TABLE,     CREATE SEQUENCE, CREATE VIEW, CREATE STREAM, CREATE DYNAMIC TABLE ON ALL SCHEMAS IN DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER;
GRANT ALL PRIVILEGES ON SCHEMA DEMO_DEV_ANALYTICS.INTERNAL TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER;

CREATE OR REPLACE DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER;
GRANT USAGE ON DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT USAGE ON SCHEMA DEMO_DEV_ANALYTICS.STAGING TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DEV_ANALYTICS.STAGING TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DEV_ANALYTICS.STAGING TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.STAGING TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.STAGING TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT USAGE ON SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.INTERMEDIATE TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT USAGE ON SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT USAGE ON SCHEMA DEMO_DEV_ANALYTICS.SEEDS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DEV_ANALYTICS.SEEDS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DEV_ANALYTICS.SEEDS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.SEEDS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.SEEDS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;

CREATE OR REPLACE DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;
GRANT DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_ANALYST;
GRANT USAGE ON DATABASE DEMO_DEV_ANALYTICS TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;
GRANT USAGE ON SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DEV_ANALYTICS.MART TO DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_VIEWER;

USE ROLE SECURITYADMIN;
GRANT DATABASE ROLE DEMO_DEV_ANALYTICS.DATA_DEVELOPER TO ROLE DEMO_DATA_DEVELOPER;
GRANT DATABASE ROLE DEMO_DEV_ANALYTICS.ADMIN TO ROLE DEMO_ADMIN;

USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE DEMO_UAT_ANALYTICS CLONE DEMO_DEV_ANALYTICS;
CREATE OR REPLACE DATABASE DEMO_PROD_ANALYTICS CLONE DEMO_DEV_ANALYTICS;

USE ROLE SECURITYADMIN;
GRANT DATABASE ROLE DEMO_UAT_ANALYTICS.DATA_ANALYST TO ROLE DEMO_DATA_ANALYST;
GRANT DATABASE ROLE DEMO_PROD_ANALYTICS.DATA_VIEWER TO ROLE DEMO_DATA_VIEWER;
